/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecoverPasswordRouteImport } from './routes/recoverPassword'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoClienteRouteImport } from './routes/historicoCliente'
import { Route as DadosClienteRouteImport } from './routes/dadosCliente'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminVendasRouteImport } from './routes/admin/vendas'
import { Route as AdminValorRecebidoRouteImport } from './routes/admin/valor-recebido'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminFaltaEstoqueRouteImport } from './routes/admin/falta-estoque'
import { Route as AdminCompraClienteRouteImport } from './routes/admin/compra-cliente'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'

const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recoverPassword',
  path: '/recoverPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoClienteRoute = HistoricoClienteRouteImport.update({
  id: '/historicoCliente',
  path: '/historicoCliente',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosClienteRoute = DadosClienteRouteImport.update({
  id: '/dadosCliente',
  path: '/dadosCliente',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendasRoute = AdminVendasRouteImport.update({
  id: '/admin/vendas',
  path: '/admin/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminValorRecebidoRoute = AdminValorRecebidoRouteImport.update({
  id: '/admin/valor-recebido',
  path: '/admin/valor-recebido',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaltaEstoqueRoute = AdminFaltaEstoqueRouteImport.update({
  id: '/admin/falta-estoque',
  path: '/admin/falta-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompraClienteRoute = AdminCompraClienteRouteImport.update({
  id: '/admin/compra-cliente',
  path: '/admin/compra-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/carrinho': typeof CarrinhoRoute
  '/cliente': typeof ClienteRoute
  '/dadosCliente': typeof DadosClienteRoute
  '/historicoCliente': typeof HistoricoClienteRoute
  '/login': typeof LoginRoute
  '/recoverPassword': typeof RecoverPasswordRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/compra-cliente': typeof AdminCompraClienteRoute
  '/admin/falta-estoque': typeof AdminFaltaEstoqueRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/valor-recebido': typeof AdminValorRecebidoRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/carrinho': typeof CarrinhoRoute
  '/cliente': typeof ClienteRoute
  '/dadosCliente': typeof DadosClienteRoute
  '/historicoCliente': typeof HistoricoClienteRoute
  '/login': typeof LoginRoute
  '/recoverPassword': typeof RecoverPasswordRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/compra-cliente': typeof AdminCompraClienteRoute
  '/admin/falta-estoque': typeof AdminFaltaEstoqueRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/valor-recebido': typeof AdminValorRecebidoRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar': typeof CadastrarRoute
  '/carrinho': typeof CarrinhoRoute
  '/cliente': typeof ClienteRoute
  '/dadosCliente': typeof DadosClienteRoute
  '/historicoCliente': typeof HistoricoClienteRoute
  '/login': typeof LoginRoute
  '/recoverPassword': typeof RecoverPasswordRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/compra-cliente': typeof AdminCompraClienteRoute
  '/admin/falta-estoque': typeof AdminFaltaEstoqueRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/valor-recebido': typeof AdminValorRecebidoRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar'
    | '/carrinho'
    | '/cliente'
    | '/dadosCliente'
    | '/historicoCliente'
    | '/login'
    | '/recoverPassword'
    | '/admin/categorias'
    | '/admin/compra-cliente'
    | '/admin/falta-estoque'
    | '/admin/produtos'
    | '/admin/valor-recebido'
    | '/admin/vendas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar'
    | '/carrinho'
    | '/cliente'
    | '/dadosCliente'
    | '/historicoCliente'
    | '/login'
    | '/recoverPassword'
    | '/admin/categorias'
    | '/admin/compra-cliente'
    | '/admin/falta-estoque'
    | '/admin/produtos'
    | '/admin/valor-recebido'
    | '/admin/vendas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/cadastrar'
    | '/carrinho'
    | '/cliente'
    | '/dadosCliente'
    | '/historicoCliente'
    | '/login'
    | '/recoverPassword'
    | '/admin/categorias'
    | '/admin/compra-cliente'
    | '/admin/falta-estoque'
    | '/admin/produtos'
    | '/admin/valor-recebido'
    | '/admin/vendas'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRoute: typeof CadastrarRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ClienteRoute: typeof ClienteRoute
  DadosClienteRoute: typeof DadosClienteRoute
  HistoricoClienteRoute: typeof HistoricoClienteRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminCompraClienteRoute: typeof AdminCompraClienteRoute
  AdminFaltaEstoqueRoute: typeof AdminFaltaEstoqueRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminValorRecebidoRoute: typeof AdminValorRecebidoRoute
  AdminVendasRoute: typeof AdminVendasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recoverPassword': {
      id: '/recoverPassword'
      path: '/recoverPassword'
      fullPath: '/recoverPassword'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historicoCliente': {
      id: '/historicoCliente'
      path: '/historicoCliente'
      fullPath: '/historicoCliente'
      preLoaderRoute: typeof HistoricoClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dadosCliente': {
      id: '/dadosCliente'
      path: '/dadosCliente'
      fullPath: '/dadosCliente'
      preLoaderRoute: typeof DadosClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendas': {
      id: '/admin/vendas'
      path: '/admin/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/valor-recebido': {
      id: '/admin/valor-recebido'
      path: '/admin/valor-recebido'
      fullPath: '/admin/valor-recebido'
      preLoaderRoute: typeof AdminValorRecebidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/falta-estoque': {
      id: '/admin/falta-estoque'
      path: '/admin/falta-estoque'
      fullPath: '/admin/falta-estoque'
      preLoaderRoute: typeof AdminFaltaEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compra-cliente': {
      id: '/admin/compra-cliente'
      path: '/admin/compra-cliente'
      fullPath: '/admin/compra-cliente'
      preLoaderRoute: typeof AdminCompraClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRoute: CadastrarRoute,
  CarrinhoRoute: CarrinhoRoute,
  ClienteRoute: ClienteRoute,
  DadosClienteRoute: DadosClienteRoute,
  HistoricoClienteRoute: HistoricoClienteRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminCompraClienteRoute: AdminCompraClienteRoute,
  AdminFaltaEstoqueRoute: AdminFaltaEstoqueRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminValorRecebidoRoute: AdminValorRecebidoRoute,
  AdminVendasRoute: AdminVendasRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
